language: python
sudo: required
python:
    - "2.7"
addons:
  postgresql: "9.5"
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
after_success:
    - coveralls
branches:
  except:
    - /test_release_\d+/
    - test_release
deploy:
  # Create a release tag for successful master builds
  - provider: script
    script: bash bin/travis-push.sh
    on:
      branch: fix-tagging
